### ISSUE TITLE
Support for WebP

### ISSUE THREAD

**Issue by WardBenjamin** [kamadak/exif-rs#16]
According to #12, support for EXIF data in WebP files can probably be accomplished using img-parts (which seems to have some partial support for WebP files) and kamadak-exif for parsing the raw Exif block. Are you interested in supporting this format natively as well?

**Comment by kamadak** [comment]
Yes, I will add support for WebP.
Also, img-parts + kamadak-exif will definitely work.

**Comment by kamadak** [comment]
WebP support is available in version 0.5.4.
