### ISSUE TITLE
Request for example usages

### ISSUE THREAD

**Issue by tungel** [kamadak/exif-rs#2]
Hi, thank you so much for making this library.

I'm new to Rust and find that it's quite hard to use this library. Basically I would like to get some basic info from an JPG image like: width, height, datetime taken, resolution, ...

Could you please include a simple code snippet that demonstrate how to get those data from an image's exif?

**Comment by WrinklyNinja** [comment]
Not a maintainer, but if you just want an example, my utility [Yore](https://github.com/WrinklyNinja/yore) uses this library, you can see how I get timestamps and GPS metadata [here](https://github.com/WrinklyNinja/yore/blob/master/src/photo.rs). 

I agree though, examples would be good. Maybe I can contribute my code as one, if I make some time too.

**Comment by tungel** [comment]
@WrinklyNinja  Thank you very much for the link to your code. I came up with a simple snippet that gets the datetime when the photo was created:

```rust
let file = std::fs::File::open("photo.jpg").expect("Error opening pic file");
let mut reader = exif::Reader::new(&mut std::io::BufReader::new(&file)).unwrap();

// Created date time
if let Some(field) = reader.get_field(exif::tag::DateTimeOriginal, false) {
    if let exif::Value::Ascii(_) = field.value {
        println!("Created datetime = {}", field.value.display_as(field.tag))
    }
}
```
That works fine, and I can get a few more exif fields too. However, I can't find a way to get the image resolution (width, height) with this library. Is there anything that I'm missing?

**Comment by kamadak** [comment]
I have added an example in the repository, which includes how to get [the image width](https://github.com/kamadak/exif-rs/blob/0.2.3/examples/reading.rs#L51-L57) and [the image resolution](https://github.com/kamadak/exif-rs/blob/0.2.3/examples/reading.rs#L59-L67).  When [printing values](https://github.com/kamadak/exif-rs/blob/0.2.3/examples/reading.rs#L46-L48), `Value::display_as` can be used without matching against `Value` variants.  So, if @tungel's question is about printing the value, the following code would do it.

```rust
if let Some(field) = reader.get_field(exif::tag::ImageWidth, false) {
    println!("Image width = {}", field.value.display_as(field.tag))
}
```

I can imagine the difficulty @tungel is feeling.  Using exif-rs requires some knowledge on Exif for now: DateTime is encoded in ASCII, ImageWidth in SHORT or LONG, XResolution in RATIONAL, and so on.

I guess adding high-level APIs (see an example below) to exif-rs may be a good idea.  However, I also feel that such APIs should support other formats than Exif, so they should reside in a separate high-level library that is built on top of exif-rs and other format-specific libraries.

```rust
struct EasyToUseWrapperForReader {
    inner: Reader,
}

impl EasyToUseWrapperForReader {
    fn image_width(&self, thumbnail: bool) -> Option<u32> {
        self.inner.get_field(tag::ImageWidth, thumbnail)
            .and_then(|f| f.value.get_uint(0))
    }

    fn date_time(&self, thumbnail: bool) -> Option<DateTime> {
        self.inner.get_field(tag::DateTime, thumbnail)
            .and_then(|f| match f.value {
                Value::Ascii(ref vec) if !vec.is_empty() => DateTime::from_ascii(vec[0]).ok(),
                _ => None,
            })
    }

    // Many dedicated methods for popular fields follow...
}
```

**Comment by tungel** [comment]
Cool. Thank you very much for the detail info. I guess this issue can now be closed.

**Comment by virtualritz** [comment]
I think because `exif::tag` is deprecated the above code does't work any more? Or am I missing something. Could you supply an updated example wrapper `date_time()` returning an `Option<DateTime>`?
