### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by kalev** [kamadak/exif-rs#25]
I am packaging the kamadak-exif crate for Fedora and we have a requirement to ship license files. Please add a separate license file to git (named LICENSE or similar). Thanks!

**Comment by kamadak** [comment]
Could you please point me to a URL where that requirement is specified in the Fedora website?

**Comment by kalev** [comment]
Sure, it's here: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by kamadak** [comment]
Thanks, but "that file, containing the text of the license(s) for the package must be included in %license" is applicable only "if the source package includes the text of the license(s) in its own file"?

(I am not opposed to adding a separate file, but want to understand what the exact requirement is.)

**Comment by kalev** [comment]
Sorry for the slow reply. I see you've already added the LICENSE file in https://github.com/kamadak/exif-rs/commit/1f512e1178301d35667f3c0325ace231da1b9077 - awesome, thank you!

> Thanks, but "that file, containing the text of the license(s) for the package must be included in %license" is applicable only "if the source package includes the text of the license(s) in its own file"?

The text you quoted continues after the first paragraph and talks about what to do when a license requires that the full license text be included. In this case, the BSD license actually requires it:

```
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
```

Which means that we need to distribute the license because the license terms require it. We could of course just add a generic BSD license, but it makes things a lot easier if we can just take the license text from upstream and not have  to worry about subtly getting it wrong if we attempt to add it ourselves downstream. So adding it upstream was very helpful.

Thanks a lot for fixing it!

**Comment by kamadak** [comment]
The license text has been there in the repository from the beginning: <https://github.com/kamadak/exif-rs/blob/e6e759af11e6ed143d04bf981069ad99865226e9/src/lib.rs#L2-L24>

If I would aware that the point of your request was not a "separate" file but the "text itself", we could solve this issue earlier.  Thanks anyway.

**Comment by kalev** [comment]
No, my request was for a separate file, actually. It helps a lot because we can take the separate file and include it in the binary package, and we can be sure it's correct because the file comes directly from upstream without any modifications on our part.
