### ISSUE TITLE
InvalidFormat("Unexpected next IFD")

### ISSUE THREAD

**Issue by evanw** [kamadak/exif-rs#31]
I have a JPEG image generated by a [FLIR camera](https://www.flir.com/browse/home-amp-outdoor/mobile-accessories/):

<img height=250 src="https://user-images.githubusercontent.com/406394/221917482-753d02fc-3ef5-438d-8eec-21fefbe2af27.jpg">

I traced through this library and it looks like the child IFD for `Tag::GPSInfoIFDPointer` has a `next_ifd_offset` of -1 (i.e. `0xFF_FF_FF_FF`) instead of 0, which causes this library to fail with `InvalidFormat("Unexpected next IFD")`.

The file is able to be parsed using `exiftool`. I traced through its Perl code and it seems like `exiftool` only [parses the next IFD](https://github.com/exiftool/exiftool/blob/7ee524e7895133140d50dc27284aee7890efe278/lib/Image/ExifTool/Exif.pm#L6751-L6752) if the tag is [known to have a next IFD](https://github.com/exiftool/exiftool/blob/7ee524e7895133140d50dc27284aee7890efe278/lib/Image/ExifTool/Exif.pm#L5913). So maybe it's safe to just ignore the next IFD offset for child IFDs instead of validating the offset? That would allow this library to read EXIF metadata from files like this one. What do you think?

**Comment by kamadak** [comment]
Your analysis is correct.  I am adding a more general "recovery from error" mode to the version 0.6 of this library.

**Comment by gzsombor** [comment]
I've noticed, that someone already hacked a solution for this problem : https://github.com/vabock/exif-rs/commit/76ee369bf4766af200679f17e216dfda51a262e0
This solved my similar problem, maybe you can merge this fix, and release the library. What do you think?

**Comment by kamadak** [comment]
The file can be read with `Reader::continue_on_error` enabled, which was added in 710c1a3.

**Comment by JosiahParry** [comment]
I just ran into this issue but the `continue_on_error()` did not resolve it. The same data can be read using other exif libraries. 

Image below 
<details> 

![241011115644_Water_Site_1040_Birch_Creek_in_Pilot_Rock](https://github.com/user-attachments/assets/21b0a4e2-3b5d-4e2a-9ce1-7422f7515551)

</details>

**Comment by kamadak** [comment]
Published version 0.6, which supports the continue-on-error mode.
