### ISSUE TITLE
Unexpected "Truncated IFD count", exiftool is fine

### ISSUE THREAD

**Issue by oliverbestmann** [kamadak/exif-rs#34]
![IMG_20191012_171303](https://github.com/kamadak/exif-rs/assets/6551584/2b57ccfe-c863-403e-aee1-a2b80c5e883e)

exif-rs tells me "Truncated IFD count" when reading exif data for this file, exiftool is fine and does not complain.

Looks like github includes the original image, to be on the safe side, image sha1 is `d43813088933be5b76f99905521abaa35e9c52d7`.

**Comment by kamadak** [comment]
The file can be read with `Reader::continue_on_error` enabled, which was added in 710c1a3.

**Comment by kamadak** [comment]
Published version 0.6, which supports the continue-on-error mode.
