### ISSUE TITLE
"Truncated field value", exiftool is fine

### ISSUE THREAD

**Issue by oliverbestmann** [kamadak/exif-rs#35]
`exif-rs` gives me `Truncated field value` while `exiftool` is fine reading the image.

The image sha1 is `62e07a2e8c76cb6fb5e5cff70526b1e382eae423`

![IMG_20130311_111917](https://github.com/kamadak/exif-rs/assets/6551584/1070c626-d1a5-4177-8f09-9b30b80f2882)

**Comment by kamadak** [comment]
The file can be read with `Reader::continue_on_error` enabled, which was added in 710c1a3.

**Comment by kamadak** [comment]
Published version 0.6, which supports the continue-on-error mode.
