### ISSUE TITLE
Release new version on crates.io?

### ISSUE THREAD

**Issue by evdokimovs** [kamadak/exif-rs#44]
Do you plan to release latest (`master`) version to the crates.io? Latest release was 2 years ago, but I noticed that you have added some useful features to the library (most interesting for me is 710c1a3) and it will be more convenient to use it from crates.io instead of git.

**Comment by evdokimovs** [comment]
@kamadak

**Comment by evdokimovs** [comment]
@kamadak ,

I'm still interested in this.

**Comment by evdokimovs** [comment]
@kamadak ,

Any updates on this?

**Comment by kamadak** [comment]
Published 0.6, thanks.
